# Generated by Django 2.0.7 on 2018-07-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
